### ISSUE TITLE
Support installation through gofish

### ISSUE THREAD

**Issue by karuppiah7890** [thecasualcoder/lazy-connect#17]
https://gofi.sh

**Comment by arunvelsriram** [comment]
As `brew` is widely used and [manual installation](https://github.com/thecasualcoder/lazy-connect#manual) is also possible, am not going to spend effort on this.

Please raise Pull Request.

**Comment by karuppiah7890** [comment]
Sure 👍

**Comment by karuppiah7890** [comment]
Closing this in favor of https://github.com/thecasualcoder/fish-food/issues/3
