### ISSUE TITLE
Sometimes script throws error on lazyconnect

### ISSUE THREAD

**Issue by thamaraiselvam** [thecasualcoder/lazy-connect#20]
the following error is been thrown

```
600:666: execution error: System Events got an error: Can’t get button "Authentication Settings…" of group 1 of window 1 of process "System Preferences". (-1728)
```
May be should add a delay?

**Comment by thamaraiselvam** [comment]
Another error occurs when trying to connect already connected VPN because the `connect` button changed into `disconnect`

```
1016:1065: execution error: System Events got an error: Can’t get button "Connect" of group 1 of window 1 of process "System Preferences". (-1728)
```

**Comment by thamaraiselvam** [comment]
It occurs when trying to connect VPN is already connected because 

`osx_vpn_name="${vpn_name/Connect /}, Not Connected"`

gets only **Not Connected** VPNs

**Comment by thamaraiselvam** [comment]
So let's suppress error by checking `Authentication Settings` exist? or remove **Not Connected** from `osx_vpn_name="${vpn_name/Connect /}, Not Connected"`?

**Comment by thamaraiselvam** [comment]
Sometimes it happens for not connected VPNs as well.

**Comment by jpninanjohn** [comment]
Closing as its duplicate
